apiVersion: v1
kind: Service
metadata:
  name: doom-service
  labels:
    app: doom-deployment
spec:
  ports:
    - port: 6901
      targetPort: 6901
  selector:
    app: doom-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom-deployment
spec:
  selector:
    matchLabels:
      app: doom-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: doom-deployment
    spec:
      containers:
        - name: doom-container
          image: kasmweb/doom:1.13.0
          ports:
            - containerPort: 6901
          env:
            - name: VNC_PW
              value: "password"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
